### ISSUE TITLE
Error while following setup instructions

### ISSUE THREAD

**Issue by crcastle** [hivejs/docs#1]
I just followed the instructions here: https://hivejs.gitbooks.io/hive-js-documentation/content/setup/installation.html

I'm getting the following error when I run `hive -s http -s queue`:
```
❯ hive -s http -s queue
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'port' of undefined
    at module.exports (/Users/crcastle/src/hive/node_modules/hive-broadcast-smokesignal/node.js:8:16)
    at Object.setup (/Users/crcastle/src/hive/node_modules/hive-broadcast-smokesignal/index.js:29:3)
    at Architect.registerPlugin (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:491:16)
    at next (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:471:13)
    at register (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:535:9)
    at Object.setup (/Users/crcastle/src/hive/node_modules/hive-core/components/services/index.js:49:3)
    at Architect.registerPlugin (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:491:16)
    at next (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:471:13)
    at register (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:535:9)
    at Object.setup (/Users/crcastle/src/hive/node_modules/hive-core/components/ot/index.js:33:3)
    at Architect.registerPlugin (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:491:16)
    at next (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:471:13)
    at register (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:535:9)
    at Object.setup (/Users/crcastle/src/hive/node_modules/hive-core/components/logger/index.js:32:3)
    at Architect.registerPlugin (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:491:16)
    at next (/usr/local/lib/node_modules/hivejs/node_modules/architect/architect.js:471:13)
```

Here's a screen recording of the setup process I followed: http://cl.ly/2B0I3a1K2F2n

Also:
```
❯ node -v
v5.8.0

~/src/hive
❯ npm -v
3.7.3
```

Can you help me figure out what I'm doing wrong?  Thanks!

**Comment by marcelklehr** [comment]
First of all, thanks for taking the time to give feedback. Yep, there's a step missing. You need to set the NODE_ENV env var and, just to be sure, for the time being you may want to use hive-broadcast-memory instead of smokesignal -- I'm not testing the latter regularly.

**Comment by crcastle** [comment]
Thanks!  That got me farther, but now I get a 404 and response body "Not Found" when I go to `http://localhost:1235`.  Here's the output of the hive process.
```
~/src/hive
❯ NODE_ENV=development hive -s http
[2016-03-11 13:07:09.809] [DEBUG] hooks - calling http:listening
[2016-03-11 13:07:09.841] [DEBUG] hooks - calling orm:initialize
[2016-03-11 13:07:09.846] [DEBUG] hooks - calling models:load
[2016-03-11 13:07:09.847] [DEBUG] hooks - calling models:loaded
[2016-03-11 13:07:09.884] [DEBUG] hooks - calling orm:initialized
[2016-03-11 13:07:15.528] [INFO] http - GET /
```

p.s. I chose `hive-broadcast-memory` (instead of smoke signal) this time.
p.p.s. Happy to make a pull request to the docs once I get this working!

**Comment by marcelklehr** [comment]
Yup, that's because there is nothing at / yet :)
You can try `/documents/1`, log in as a guest, then you'll see a 404 message, but in the browser console you can run `store.dispatch({type: 'API_DOCUMENT_CREATE', payload: {type:'text/plain'}})` to create it ;) -- I'm working on a GUI for this...

**Comment by marcelklehr** [comment]
beta.hivejs.org is live with the latest code again, btw :)

**Comment by crcastle** [comment]
Great, thanks!  That makes sense.

I played a bit with it at beta.hivejs.org.  Thanks for putting that up.  Great to see the functionality live to get a better idea of what you are aiming at creating.

Still unable to get things working properly on my local machine (well, with just a few minutes of troubleshooting).

I went to `http://localhost:1235/documents/1` and get some errors in the JS console:
![JS Errors](http://cl.ly/102G3409363m/Screen%20Shot%202016-03-12%20at%202.21.42%20PM.png)

So then I removed the 's' from 'https' in development.json like this
```
{
  "ui": {
    "baseURL": "http://localhost:1235"
  },
...
```

This got me a little further, but I get errors in the JS console and server now:
![JS Errors again](http://cl.ly/450z3616160T/Screen%20Shot%202016-03-12%20at%202.25.37%20PM.png)

and from the server process:
```
❯ NODE_ENV=development hive -s http
[2016-03-12 14:25:21.787] [DEBUG] hooks - calling http:listening
[2016-03-12 14:25:21.802] [DEBUG] hooks - calling orm:initialize
[2016-03-12 14:25:21.803] [DEBUG] hooks - calling models:load
[2016-03-12 14:25:21.804] [DEBUG] hooks - calling models:loaded
[2016-03-12 14:25:21.837] [DEBUG] hooks - calling orm:initialized
[2016-03-12 14:25:24.851] [INFO] http - GET /documents/1
[2016-03-12 14:25:24.923] [INFO] http - GET /build.css
[2016-03-12 14:25:24.926] [INFO] http - GET /build.js
[2016-03-12 14:25:29.191] [ERROR] http - Error: Cannot find module 'cldr-data/supplemental/ordinals.json' from '/Users/crcastle/src/hive/node_modules/hive-ui'
    at /Users/crcastle/src/hive/node_modules/resolve/lib/async.js:46:17
    at process (/Users/crcastle/src/hive/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/crcastle/src/hive/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/crcastle/src/hive/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/crcastle/src/hive/node_modules/resolve/lib/async.js:92:31)
    at /Users/crcastle/src/hive/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
[2016-03-12 14:25:30.800] [INFO] http - GET /build.css
```

Regardless, this all looks pretty awesome, but I'm going to try to use your other project, [`marcelklehr/gulf`](https://github.com/marcelklehr/gulf), for my needs.  I'm putting together a really simple webrtc video/audio + collaborative coding app.  Really simple like no text chatting, simple authentication (custom naming for the conference room and document).  I think gulf will be better to incorporate because 1) it will be simpler for me to learn how to use and debug and 2) it doesn't have extra functionality I don't need.

Thanks again for all your work on this stuff!  I've learned a ton about collaborative editing and OT from your projects!

**Comment by marcelklehr** [comment]
Oh, yes, the https is wrong :)

That's perfectly understandable. Hive.js is not suitable for everyone, of course, although I'm trying hard to keep the core slim and tight (most of the functionality you can see in the demo is provided by plugins).

Thank you for the feedback, I'm always glad if my work inspires other people. Good luck with your project, and be sure to check up on hive.js from time to time, it's not quite ready for production yet, but it might be when you are in need again ;)

**Comment by marcelklehr** [comment]
I've fixed hive-init(1)'s default config, and added NODE_ENV to the setup docs. I will investigate the cldr-data error.

**Comment by marcelklehr** [comment]
I just hit the cldr-data error while testing -- simply re-running `npm install` should do the trick ;)

**Comment by crcastle** [comment]
Thanks!

p.s. Got my app running with gulf.  I'll share it with you through that repo in case you want to add it to the Examples section of the readme.

**Comment by marcelklehr** [comment]
Awesome! :)
